# Generated by Django 3.0.8 on 2022-12-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='files/covers')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
