# Generated by Django 3.0.8 on 2022-12-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgeGenAPI', '0002_auto_20221205_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='created_date',
        ),
    ]
