# Generated by Django 3.0.8 on 2020-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('play_link', models.CharField(default='#', max_length=200)),
                ('itch_link', models.CharField(default='#', max_length=200)),
                ('image', models.ImageField(upload_to='gameimages')),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=20)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
