# Generated by Django 3.0.8 on 2020-12-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='play_link',
        ),
    ]
