# Generated by Django 3.0.8 on 2020-12-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_game_play_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
