# Generated by Django 3.0.8 on 2020-12-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20201212_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
