# Generated by Django 3.0.8 on 2020-12-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20201212_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
