# Generated by Django 3.0.8 on 2020-12-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20201223_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scrapable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='scrapable',
            field=models.BooleanField(default=True),
        ),
    ]
